# =========================================================================
# Spring-related.
spring.config.activate.on-profile=localhost
spring.config.import=optional:file:${user.home}/.${user.name}-conf/uh-groupings-api-overrides.properties

# =========================================================================
# MailHog Email Service Settings.
spring.mail.host=localhost
spring.mail.port=1025
email.send.recipient=RECIPIENT
email.send.from=SENDER
email.is.enabled=false

# =========================================================================
# OpenAPI 3 Swagger UI Settings (https://springdoc.org/properties.html).
springdoc.swagger-ui.displayOperationId=true
springdoc.swagger-ui.displayRequestDuration=true

# =========================================================================
app.environment=localhost